version: '2'
services:
  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=muon
      - RABBITMQ_DEFAULT_PASS=microservices
    image: rabbitmq:3.6.2-management
    #ports:
    #  - "5672:5672"
    #  - "15672:15672"

  nodetests:
    build:
      context: .
    links:
      - rabbitmq
    environment:
      - MUON_URL=amqp://muon:microservices@rabbitmq
    volumes:
      - ./test-results/:/usr/src/app/test-results
