rabbitmq:
  image: rabbitmq:3.5.4-management
  ports:
    - "15672:15672"
    - "5672:5672"
  environment:
    - RABBITMQ_DEFAULT_USER=muon
    - RABBITMQ_DEFAULT_PASS=microservices
muon-java-tck-endpoint:
  build: .
  links:
    - rabbitmq
muon-tck:
  image: simplicityitself/muon-amqp-protocol-spec
  links:
    - rabbitmq
  volumes:
    - ./test-results:/app/test-results/
